name: EX-10 Continuos Delivery

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: tiny-health-app
  CONTAINER_NAME: tiny-health-container
  APP_PORT: "8000"
  AWS_REGION: us-east-1

  ECR_REGISTRY: 998718205915.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: mahomud

jobs:
  deploy-package:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::998718205915:role/badrgithublabrole
          aws-region: ${{ env.AWS_REGION }}

      - name: Fetch the caller identity
        run: aws sts get-caller-identity

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan -H ${{ vars.EC2_IP }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Test SSH
        run: |
          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} \
          "echo Connected && whoami && hostname"

      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Copy scripts to EC2
        run: |
          scp -r -i ~/.ssh/ec2_key ./scripts \
          ubuntu@${{ vars.EC2_IP }}:/tmp/

      - name: Prepare EC2
        run: |
          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} \
          "chmod +x /tmp/scripts/assessment/prepare-ubuntu-vm.sh && \
          sudo /tmp/scripts/assessment/prepare-ubuntu-vm.sh"

      - name: Get ECR login password
        id: ecr
        run: |
          echo "PASSWORD=$(aws ecr get-login-password --region $AWS_REGION)" >> $GITHUB_OUTPUT

      - name: Login & Pull image on EC2
        run: |
          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} \
          "echo '${{ steps.ecr.outputs.PASSWORD }}' | \
          docker login --username AWS --password-stdin ${ECR_REGISTRY} && \
          docker pull ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"

      - name: Stop old container
        run: |
          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} \
          "docker rm -f ${CONTAINER_NAME} || true"

      - name: Start container
        run: |
          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} \
          "docker run -d \
            --name ${CONTAINER_NAME} \
            -p ${APP_PORT}:8000 \
            ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"

      - name: Show running containers
        run: |
          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} "docker ps"


      - name: Wait & Validate ON EC2
        run: |
          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} "
            echo '==== WAIT FOR APP ====';
            for i in {1..10}; do
              curl -f http://localhost:${APP_PORT}/health && exit 0
              echo 'Waiting for app...'
              sleep 2
            done

            echo '==== VALIDATION FAILED ====';
            
            echo '==== CURL TEST ====';
            curl -v http://localhost:${APP_PORT}/health || true;

            echo '==== DOCKER LOGS ====';
            docker logs ${CONTAINER_NAME} || true;

            echo '==== PORT CHECK ====';
            ss -tulnp | grep 8000 || true;

            exit 1
          "

      - name: Stop container (always)
        if: always()
        run: |
          ssh -i ~/.ssh/ec2_key ubuntu@${{ vars.EC2_IP }} \
          "docker rm -f ${CONTAINER_NAME} || true"
